org: potoncito
service: mediprior

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  stage: dev
  iam:
    role: arn:aws:iam::430968800564:role/LabRole
  environment:
    JOBS_TABLE: !Ref JobsTable
    PATIENTS_TABLE: !Ref PatientsTable
    SQS_QUEUE_URL: !Ref MainQueue
    DLQ_URL: !Ref DeadLetterQueue

functions:
  ingester:
    handler: functions/ingester.handler
    timeout: 29
    events:
      - httpApi:
          path: /upload
          method: POST

  processor:
    handler: functions/processor.handler
    timeout: 29
    reservedConcurrency: 5
    environment:
      GROQ_API_KEY: ${env:GROQ_API_KEY}
    events:
      - sqs:
          arn: !GetAtt MainQueue.Arn
          batchSize: 1

  getter:
    handler: functions/getter.handler
    timeout: 10
    events:
      - httpApi:
          path: /results/{jobId}
          method: GET
  retrier:
    handler: functions/retrier.handler
    timeout: 29
    events:
      - httpApi:
          path: /retry-failed
          method: POST
      - httpApi:
          path: /retry-failed
          method: OPTIONS

resources:
  Resources:
    MainQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: mediprior-main-queue
        VisibilityTimeout: 120
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
          maxReceiveCount: 3

    DeadLetterQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: mediprior-dlq
        MessageRetentionPeriod: 1209600

    JobsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: mediprior-jobs
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: jobId
            AttributeType: S
        KeySchema:
          - AttributeName: jobId
            KeyType: HASH

    PatientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: mediprior-patients
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: jobId
            AttributeType: S
          - AttributeName: patientId
            AttributeType: S
        KeySchema:
          - AttributeName: jobId
            KeyType: HASH
          - AttributeName: patientId
            KeyType: RANGE

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: false
